/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Site6RouteImport } from './routes/site6'
import { Route as Site5RouteImport } from './routes/site5'
import { Route as Site4RouteImport } from './routes/site4'
import { Route as Site3RouteImport } from './routes/site3'
import { Route as Site2RouteImport } from './routes/site2'
import { Route as Site1RouteImport } from './routes/site1'
import { Route as IndexRouteImport } from './routes/index'

const Site6Route = Site6RouteImport.update({
  id: '/site6',
  path: '/site6',
  getParentRoute: () => rootRouteImport,
} as any)
const Site5Route = Site5RouteImport.update({
  id: '/site5',
  path: '/site5',
  getParentRoute: () => rootRouteImport,
} as any)
const Site4Route = Site4RouteImport.update({
  id: '/site4',
  path: '/site4',
  getParentRoute: () => rootRouteImport,
} as any)
const Site3Route = Site3RouteImport.update({
  id: '/site3',
  path: '/site3',
  getParentRoute: () => rootRouteImport,
} as any)
const Site2Route = Site2RouteImport.update({
  id: '/site2',
  path: '/site2',
  getParentRoute: () => rootRouteImport,
} as any)
const Site1Route = Site1RouteImport.update({
  id: '/site1',
  path: '/site1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/site1': typeof Site1Route
  '/site2': typeof Site2Route
  '/site3': typeof Site3Route
  '/site4': typeof Site4Route
  '/site5': typeof Site5Route
  '/site6': typeof Site6Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/site1': typeof Site1Route
  '/site2': typeof Site2Route
  '/site3': typeof Site3Route
  '/site4': typeof Site4Route
  '/site5': typeof Site5Route
  '/site6': typeof Site6Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/site1': typeof Site1Route
  '/site2': typeof Site2Route
  '/site3': typeof Site3Route
  '/site4': typeof Site4Route
  '/site5': typeof Site5Route
  '/site6': typeof Site6Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/site1'
    | '/site2'
    | '/site3'
    | '/site4'
    | '/site5'
    | '/site6'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/site1' | '/site2' | '/site3' | '/site4' | '/site5' | '/site6'
  id:
    | '__root__'
    | '/'
    | '/site1'
    | '/site2'
    | '/site3'
    | '/site4'
    | '/site5'
    | '/site6'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Site1Route: typeof Site1Route
  Site2Route: typeof Site2Route
  Site3Route: typeof Site3Route
  Site4Route: typeof Site4Route
  Site5Route: typeof Site5Route
  Site6Route: typeof Site6Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site6': {
      id: '/site6'
      path: '/site6'
      fullPath: '/site6'
      preLoaderRoute: typeof Site6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site5': {
      id: '/site5'
      path: '/site5'
      fullPath: '/site5'
      preLoaderRoute: typeof Site5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site4': {
      id: '/site4'
      path: '/site4'
      fullPath: '/site4'
      preLoaderRoute: typeof Site4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site3': {
      id: '/site3'
      path: '/site3'
      fullPath: '/site3'
      preLoaderRoute: typeof Site3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site2': {
      id: '/site2'
      path: '/site2'
      fullPath: '/site2'
      preLoaderRoute: typeof Site2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site1': {
      id: '/site1'
      path: '/site1'
      fullPath: '/site1'
      preLoaderRoute: typeof Site1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Site1Route: Site1Route,
  Site2Route: Site2Route,
  Site3Route: Site3Route,
  Site4Route: Site4Route,
  Site5Route: Site5Route,
  Site6Route: Site6Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
